project:
  type: website
  output-dir: docs

website:
  title: ""
  image: img/quant_workshop_logo.png
  navbar:
    search: true
    left:
      - href: index
        text: home
      - href: about
        text: about
      - href: people
        text: people
      - href: quant-shop
        text: quant-shop
      - href: research
        text: research
      - href: events
        text: events
      - href: styles/manual
        text: lab manual
      
  page-footer:
    right: "Built with love in [Quarto](https://quarto.org/)"
    left: "&copy; 2026 Quantitative Histories Workshop"
   
format:
  html:
    page-layout: full
    theme: cosmo light
    css: styles/site.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 1600px
    
editor: source